version: '3.5'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"