version: '3.5'

services:
  db:
    image: postgres:12
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_TITLE}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
  app:
    depends_on:
     - db
    build: .
    ports:
     - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    environment:
      SPRING_DATASOURCE_URL : jdbc:postgresql://db:${DB_DOCKER_PORT}/${DB_TITLE}
volumes:
  postgre_db:
    driver: local