# To get feedback in the tilt UI
# print('Hello Tiltfile')

# kubectl apply -f weather_db_deployment.yaml
# kubectl apply -f weather_db_service.yaml
k8s_yaml(['weather_db_deployment.yaml', 'weather_db_service.yaml'])
# kubectl apply -f weather_app_deployment.yaml
# kubectl apply -f weather_app_service.yaml
k8s_yaml(['weather_app_deployment.yaml', 'weather_app_service.yaml'])

# docker build -t springbootweather_app .
docker_build('springbootweather_app', '.')

# maps the port of the application to localhost:8000
k8s_resource('app', port_forwards='8000:8080')
