# Service
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    db: db
  # name of service
  name: db
spec:
  ports:
    # port forwarding for the service
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    db: db
status:
  loadBalancer: {}
