# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      springbootweather: web
  template:
    metadata:
      labels:
        springbootweather: web
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/weather_db
          image: springbootweather_app
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
