# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    db: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: db
  template:
    metadata:
      creationTimestamp: null
      labels:
        db: db
    spec:
      containers:
        # environment variables analog to docker-compose:
        - env:
            - name: POSTGRES_DB
              value: weather_db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: springuser
          # docker image used:
          image: postgres:12
          # No ImagePullPolicy given, cause this image is accessible online
          # name of the container:
          name: db
          ports:
            # Port forwarding for the database
            - containerPort: 5432
          resources: {}
      # restart policy in case the db crashes
      restartPolicy: Always
status: {}
